console.log("Hello");
console.log("Hello");

try{
    console.log(a);
} catch(err) {
    console.log("Caught an error ...");
    console.log(err);
}

console.log("Hello2");
console.log("Hello2");
console.log("Hello2");